//CONFIG
CREATE TABLE CONFIG
AS
SELECT CURRENT_DATE REPORT_DATE FROM DUAL;

//TABLE SUTJI_DM_TOTAL_GR_PER_DATE
CREATE OR REPLACE FORCE VIEW SUTJIVIEW_TOTAL_GR_PER_DATE
AS
SELECT ORDER_DATE, SUM(GROSS_REVENUE) TOTAL_GROSS_REVENUE FROM (
    SELECT (1-B.DISCOUNT)*B.UNIT_PRICE*B.QUANTITY GROSS_REVENUE, A.ORDER_DATE FROM ORDERS A
    LEFT JOIN ORDER_DETAILS B
    ON A.ORDER_ID = B.ORDER_ID
)
WHERE ORDER_DATE = (SELECT REPORT_DATE FROM CONFIG)
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE;

//TABLE SUTJI_DM_TOTAL_GR_PER_PRODUCT_PER_MONTH
CREATE OR REPLACE FORCE VIEW SUTJIVIEW_TOTAL_GR_PER_PRODUCT_PER_MONTH
AS
SELECT ORDER_MONTH, PRODUCT_NAME, SUM(GROSS_REVENUE) TOTAL_GROSS_REVENUE FROM (
    SELECT (1-B.DISCOUNT)*B.UNIT_PRICE*B.QUANTITY GROSS_REVENUE, SUBSTR(ORDER_DATE,1,7) ORDER_MONTH,                C.PRODUCT_NAME FROM ORDERS A
    LEFT JOIN ORDER_DETAILS B
    ON A.ORDER_ID = B.ORDER_ID
    LEFT JOIN PRODUCTS C
    ON B.PRODUCT_ID = C.PRODUCT_ID
)
WHERE ORDER_MONTH = (SELECT SUBSTR(REPORT_DATE,1,7) FROM CONFIG)
GROUP BY ORDER_MONTH, PRODUCT_NAME
ORDER BY ORDER_MONTH;

//TABLE SUTJI_DM_TOTAL_ORDER_PER_PRODUCT_PER_MONTH
CREATE OR REPLACE FORCE VIEW SUTJIVIEW_TOTAL_ORDER_PER_PRODUCT_PER_MONTH
AS
SELECT * FROM (
SELECT SUBSTR(A.ORDER_DATE,1,7) ORDER_MONTH, C.PRODUCT_NAME, COUNT(A.ORDER_ID) TOTAL_ORDER
FROM ORDERS A
LEFT JOIN ORDER_DETAILS B
ON A.ORDER_ID = B.ORDER_ID
LEFT JOIN PRODUCTS C
ON B.PRODUCT_ID = C.PRODUCT_ID
GROUP BY SUBSTR(A.ORDER_DATE,1,7), PRODUCT_NAME
ORDER BY COUNT(A.ORDER_ID) DESC
)
WHERE ORDER_MONTH = (SELECT SUBSTR(REPORT_DATE,1,7) FROM CONFIG);

//TABLE SUTJI_DM_TOTAL_ORDER_PER_CATEGORY_PER_MONTH
CREATE OR REPLACE FORCE VIEW SUTJIVIEW_TOTAL_ORDER_PER_CATEGORY_PER_MONTH
AS
SELECT * FROM (
SELECT SUBSTR(A.ORDER_DATE,1,7) ORDER_MONTH, D.CATEGORY_NAME, COUNT(A.ORDER_ID) TOTAL_ORDER
FROM ORDERS A
LEFT JOIN ORDER_DETAILS B
ON A.ORDER_ID = B.ORDER_ID
LEFT JOIN PRODUCTS C
ON B.PRODUCT_ID = C.PRODUCT_ID
LEFT JOIN CATEGORIES D
ON C.CATEGORY_ID = D.CATEGORY_ID
GROUP BY SUBSTR(A.ORDER_DATE,1,7), D.CATEGORY_NAME
)
WHERE ORDER_MONTH = (SELECT SUBSTR(REPORT_DATE,1,7) FROM CONFIG);

//TABLE SUTJI_DM_TOTAL_ORDER_PER_COUNTRY_PER_MONTH
CREATE OR REPLACE FORCE VIEW SUTJIVIEW_TOTAL_ORDER_PER_COUNTRY_PER_MONTH
AS
SELECT * FROM (
SELECT SUBSTR(A.ORDER_DATE,1,7) ORDER_MONTH, A.SHIP_COUNTRY, COUNT(A.ORDER_ID) TOTAL_ORDER
FROM ORDERS A
GROUP BY SUBSTR(A.ORDER_DATE,1,7), A.SHIP_COUNTRY
)
WHERE ORDER_MONTH = (SELECT SUBSTR(REPORT_DATE,1,7) FROM CONFIG);